### ISSUE TITLE
Prototype Puzzle Mechanics

### ISSUE THREAD

**Issue by MashdorDev** [MashdorDev/unbread#24]
Design and implement prototype puzzle elements. Focus on creating engaging and challenging puzzles that integrate seamlessly with the game's environment and storyline.

**Comment by GageM** [comment]
- [ ] Lever
        Lever should be able to run functions on other objects like adding force, setting destination or rotate
- [ ] Base Movable Object
        An object that can be pushed and/or pulled by the player
        An object that requires both chef and player to be pulled or pushed
- [ ] Surfaces
        Sticky surfaces that slow both enemies and the player
        Slippery surfaces
- [ ] Dynamic Environment Objects
        Objects that are not interactable but will have their own loops to make the environment look lively

**Comment by MashdorDev** [comment]
That looks great @GageM! I would only leave the to do for core gameplay - 

- [ ] Base Movable Object
An object that can be pushed and/or pulled by the player

the rest of them we can implement in the Alpha and Beta stages

**Comment by MashdorDev** [comment]
Completed
