### ISSUE TITLE
Set Up Enemy & Combat Animations

### ISSUE THREAD

**Issue by GageM** [MashdorDev/unbread#94]
- [ ] Create Donut animation blueprint
- [ ] Create Loaf animation blueprint
- [ ] Fix player throw animations
- [ ] Add animation blueprints to characters

**Comment by MashdorDev** [comment]
Hey @GageM we actully implemented the  animations in the  behaviour tree of the AI we might ditch this issue

**Comment by MashdorDev** [comment]
awesome, closed.....for now
