### ISSUE TITLE
Organize the  public code

### ISSUE THREAD

**Issue by MashdorDev** [MashdorDev/unbread#98]
we need to organized this folder as it is a big mess

![image](https://github.com/MashdorDev/unbread/assets/56084381/8ef827bf-8b3a-404a-a870-0a9864b195d9)

**Comment by GageM** [comment]
@MashdorDev this will be very difficult to do and will likely break the project. Unreal has no way to let you move C++ files to different folders after they are created

**Comment by MashdorDev** [comment]
Damn, sounds too much of wasting time, we will ditch it then.
